# This workflow:
# - runs tests on pull requests
# - runs tests on pushing to main
# - if it's a tag push and the tag starts with v, and if the tests pass,
#   deploys to PyPI using Trusted Publishers:
#   https://docs.pypi.org/trusted-publishers/
name: test-and-deploy

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  COLUMNS: 120
  FORCE_COLOR: 1


jobs:
  test:
    name: ${{ matrix.platform }} py${{ matrix.python }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        # test spec-0 earliest and latest Python versions
        # https://scientific-python.org/specs/spec-0000/
        python: ["3.10", "3.11", "3.12", "3.13"]
        include:
          - platform: macos-latest
            python: "3.12"
          - platform: windows-latest
            python: "3.11"


    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57
        with:
          version: "latest"
          python-version: ${{ matrix.python }}
          activate-environment: true

      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@5bc8de3bc71fcda7a96439571287a554901541a0 # v4.3
        with:
          qt: true
          wm: herbstluftwm

      - name: Install dependencies
        run: |
          uv sync --all-groups

      - name: Test with tox
        run: tox

      - name: Upload coverage data
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: coverage reports ${{ matrix.platform }} py ${{ matrix.python }}
          include-hidden-files: true
          path: |
            ./.coverage.*

  upload_coverage:
    if: ${{ always() }}
    secrets: inherit
    needs:
      - test
    uses: napari/shared-workflows/.github/workflows/upload_coverage.yml@main
    with:
      artifact-pattern: 'coverage reports*'

  build-and-inspect-package:
      name: Build & inspect package.
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        - uses: hynek/build-and-inspect-python-package@fe0a0fb1925ca263d076ca4f2c13e93a6e92a33e

  deploy:
    needs: [test, build-and-inspect-package]
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags')
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Download built artifact to dist/
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: Packages
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0

      - name: Publish to GitHub
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        with:
          tag_name: ${{ github.ref }}
          name: ${{ env.tag }}
          # body: add when we add release notes
          draft: false
          prerelease: ${{ contains(github.ref, 'rc') }}
          files: |
            dist/*
